### ISSUE TITLE
Move information about laws/regulations into separate document?

### ISSUE THREAD

**Issue by sysrqb** [IRTF-PEARG/draft-ip-address-privacy#27]
The [IP Privacy Protection and Law](https://github.com/ShivanKaul/draft-ip-address-privacy/blob/main/draft-ip-address-privacy-considerations.md#ip-privacy-protection-and-law) section will grow quite large with #26. Documenting the current legal implications of IP addresses seems helpful within the context of finding solutions for IP address privacy, however this draft should not be overwhelming with information on the various topics. We should consider factoring out some information into a new draft, perhaps creating a "snapshot" of the current legal landscape on this topic (similar to the [survey of censorship techniques](https://datatracker.ietf.org/doc/draft-irtf-pearg-censorship/)).

**Comment by ggx** [comment]
That would be OK for me, I have no strong position on this. Just two questions:
- Wouldn't be worth it to ask actually on the mailing list what do people prefer?
- Assuming we go for a split, I can certainly seed a draft "IP Privacy Protection and Law", should it go as an individual submission initially?

**Comment by bslassey** [comment]
I think what got merged in PR 33 fits well within the document. Anything going into further depth would probably need to be moved out. What do you think @sysrqb?

**Comment by sysrqb** [comment]
I agree, that sounds good to me. We can close this one now.
