### ISSUE TITLE
Temporary Addresses

### ISSUE THREAD

**Issue by ggx** [IRTF-PEARG/draft-ip-address-privacy#28]
I can fill this bullet.

**Comment by sysrqb** [comment]
@ggx do you still want to add more details?

**Comment by ggx** [comment]
Hi,Thank you all for the work you are doing.I am actually on vacation and not able to work on the document.However, skimming through the updates I have no further details to add.CiaoL.On 16 Aug 2023, at 19:57, Matthew Finkel ***@***.***> wrote:﻿
@ggx do you still want to add more details?

**Comment by ggx** [comment]
P.s. By details I mean about the “whole document” as for the temporary address section I will add it as soon as I am back (late august).CiaoL.On 16 Aug 2023, at 20:14, Luigi Iannone ***@***.***> wrote:﻿Hi,Thank you all for the work you are doing.I am actually on vacation and not able to work on the document.However, skimming through the updates I have no further details to add.CiaoL.On 16 Aug 2023, at 19:57, Matthew Finkel ***@***.***> wrote:﻿
@ggx do you still want to add more details?

**Comment by ggx** [comment]
Hi,

I created a pull request for a small paragraph for the temporary addresses.
